ExamApp.UI/Controllers/ExamController.cs
using ExamApp.Core.Models;
using ExamApp.Core.Services;
using ExamApp.UI.Dto;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
namespace ExamApp.UI.Controllers
{
    public class ExamController : Controller
    {
        private readonly IExamService _examService;
        private readonly IQuestionOptionService _questionOptionService;
        private readonly IQuestionService _questionService;

        public ExamController(IExamService examService, IQuestionService questionService, IQuestionOptionService questionOptionService)
        {
            this._examService = examService;
            this._questionOptionService = questionOptionService;
            this._questionService = questionService;
        }
        public IActionResult Index(int id)
        {
            try
            {
                var exam = _examService.Get(id);
                return View(exam);

            }
            catch (Exception ex)
            {

                throw;
            }

        }

        public ExamCreateViewModel CheckExam(ExamCheckViewModel viewModel)
        {
            try
            {
                var exam = _examService.Get(viewModel.Id);
                ExamCreateViewModel ec = new ExamCreateViewModel();
                ec.Id = exam.Id;
                ec.Question1Answer = (byte)(exam.Questions[0].QuestionOptions.ToList().IndexOf(exam.Questions[0].QuestionOptions.Where(x => x.IsCorrect == true).FirstOrDefault()) + 1);
                ec.Question2Answer = (byte)(exam.Questions[1].QuestionOptions.ToList().IndexOf(exam.Questions[1].QuestionOptions.Where(x => x.IsCorrect == true).FirstOrDefault()) + 1);
                ec.Question3Answer = (byte)(exam.Questions[2].QuestionOptions.ToList().IndexOf(exam.Questions[2].QuestionOptions.Where(x => x.IsCorrect == true).FirstOrDefault()) + 1);
                ec.Question4Answer = (byte)(exam.Questions[3].QuestionOptions.ToList().IndexOf(exam.Questions[3].QuestionOptions.Where(x => x.IsCorrect == true).FirstOrDefault()) + 1);

                ec.Question1UserAnswer = viewModel.Question1UserAnswer;
                ec.Question2UserAnswer = viewModel.Question2UserAnswer;
                ec.Question3UserAnswer = viewModel.Question3UserAnswer;
                ec.Question4UserAnswer = viewModel.Question4UserAnswer;

                return ec;
            }
            catch (Exception ex)
            {

                throw;
            }

        }
    }
}

ExamApp.UI/Areas/Admin/Views/Admin/Index.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">

            <div class="card card-default">

                <!-- /.card-header -->
                <div class="card-body">

                    <div class="row">
                        <div class="col-md-4">
                            <div class="card card-success">
                                <div class="card-header">
                                    <h3 class="card-title">Exam List</h3>

                                    <div class="card-tools">
                                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                            <i class="fas fa-minus"></i>
                                        </button>
                                    </div>

                                </div>

                                <div class="card-body">
                                    <a href="@Url.Action("List","Exam")"><button type="button" class="btn btn-block btn-primary">Open</button></a>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>
                        <div class="col-md-4">
                            <div class="card card-success">
                                <div class="card-header">
                                    <h3 class="card-title">Exam Create</h3>

                                    <div class="card-tools">
                                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                            <i class="fas fa-minus"></i>
                                        </button>
                                    </div>

                                </div>

                                <div class="card-body">
                                    <a href="@Url.Action("Create","Exam")"><button type="button" class="btn btn-block btn-primary">Open</button></a>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>
                </div>
            </div>

            <!-- /.form-group -->
        </div>

        <!-- /.row -->
        <!-- /.container-fluid -->
    </section>
</div>